### ISSUE TITLE
cannot import name 'data_retrieval'

### ISSUE THREAD

**Issue by mateus-k** [Priesemann-Group/covid19_inference#41] opened 2020-05-19 22:14 UTC
Hi,

I am trying to run the the 'example_bundeslaender.ipynb', but i got 'ImportError: cannot import name 'data_retrieval''

I followed the instruction at https://covid19-inference.readthedocs.io/en/latest/doc/gettingstarted.html

Am I doing something wrong?

**Comment by mgirardis** [comment] 2020-05-19 22:24
The same issue here

https://github.com/Priesemann-Group/covid19_inference/issues/42

**Comment by jdehning** [comment] 2020-05-20 00:07
Duplicate of #42

**Comment by semohr** [comment] 2020-05-20 07:38
The data_retrieval folder is somehow not shipped by installing via `pip install git+https://github.com/Priesemann-Group/covid19_inference.git`.
Has to be some package config. I have to look into this a bit more.

**Comment by semohr** [comment] 2020-05-20 07:56
Fixed by adding `find_namespace_packages()` into the setup.py. As can bee seen [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords).

**Closed** 2020-05-20 13:54 UTC
